### ISSUE TITLE
Create new Functions and Collector Documentation

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-documentation#11]
See here

https://github.com/metafacture/metafacture.github.io/tree/Morph-Documentation-Page

**Comment by acka47** [comment]
PR is at https://github.com/metafacture/metafacture.github.io/pull/9

**Comment by fsteeg** [comment]
Pushed some tweaks in https://github.com/metafacture/metafacture.github.io/commit/79ffd14e19fed16178f209def65f5f2758dd938d. In context of https://github.com/metafacture/metafacture-documentation/issues/8, we decided to use the work here as a template and content for generated function and collector references. Will be handled in new issues under https://github.com/metafacture/metafacture.github.io/issues, using content in https://github.com/metafacture/metafacture.github.io/pull/9. Closing.
