### ISSUE TITLE
Delete prettyPrinting option for encode-yaml in documentation

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-documentation#19]
This option is not supported. So I would just delete it.

**Comment by blackwinter** [comment]
Background: Jackson's `YAMLGenerator` [ignores](https://github.com/FasterXML/jackson-dataformats-text/blob/2.13/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java#L343-L349) any `PrettyPrinter` (and in version 3 it's [completely gone](https://github.com/FasterXML/jackson-dataformats-text/blob/master/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java)). There is a feature request (FasterXML/jackson-dataformats-text#43) that might help in this regard, but it hasn't been implemented yet.

**Comment by dr0i** [comment]
The option _is_ supported , as it _always_ does pretty printing. It's just superfluous.

**Comment by blackwinter** [comment]
> The option _is_ supported , as it _always_ does pretty printing.

But you can't disable pretty printing as the documentation suggests.

**Comment by dr0i** [comment]
Ah, I see. Yeah, that should be noted somehow.

**Comment by dr0i** [comment]
Closed in favour of https://github.com/metafacture/metafacture-core/pull/447.

**Comment by dr0i** [comment]
Sorry, not the issue should be closed, but another PR.

**Comment by TobiasNx** [comment]
Resolved.
