### ISSUE TITLE
Add documentation that decode-marc21 needs  UTF-8 encoding

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-documentation#23]
[See error here](https://metafacture.org/playground/?flux=%22https%3A//github.com/LibreCat/Catmandu/wiki/files/camel.usmarc%22%0A%7C+open-http%0A%7C+as-lines%0A%7C+decode-marc21%0A%7C+encode-yaml%0A%7C+print%0A%3B&active-editor=fix)

https://github.com/metafacture/metafacture-documentation/blob/master/flux-commands.md

Other decoder as `decode-aseq` and `decode-mab` have documented that they need UTF-8 but `decode-marc` has not. So where do we have to document this?

**Comment by dr0i** [comment]
Agreed to add to document `UTF-8`.
After https://github.com/metafacture/metafacture-core/issues/452 is resolved it could also be `USMARC` , so I would postpone this issue and resolve it after https://github.com/metafacture/metafacture-core/issues/452 is resolved.

**Comment by dr0i** [comment]
Skipped the `USMARC` part.
Added UTF-8 encoding to description, see https://github.com/metafacture/metafacture-documentation/blob/master/flux-commands.md#decode-marc21.
Closing.
