### ISSUE TITLE
Missing description for flux command wait-for-input

### ISSUE THREAD

**Issue by maipet** [metafacture/metafacture-documentation#30]
There is no description for flux-command "wait-for-input" on https://github.com/metafacture/metafacture-documentation/blob/master//flux-commands.md#wait-for-inputs

**Comment by dr0i** [comment]
Added this in the java class `org.metafacture.flowcontrol.CloseSuppressor`. I've to generate the `flux-commands.md` let the description appear in it.

**Comment by dr0i** [comment]
Published, see https://github.com/metafacture/metafacture-documentation/blob/master/flux-commands.md#wait-for-inputs . Please acknowledge @maipet and close this issue if all is good.
