### ISSUE TITLE
Adding links to Java Code of Fix Functions

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-documentation#38]
@maipet suggested this, I support the idea.

Not sure how to realize this, since all fix functions are in the same file.
Is there a way to link to certain Java classes in a file in github with a URL.

**Comment by blackwinter** [comment]
> Is there a way to link to certain Java classes in a file in github with a URL.

Only by line number, AFAIK. In combination with the [canonical URL](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files#press-y-to-permalink-to-a-file-in-a-specific-commit), it _could_ be an option. But quite tedious to keep up-to-date.

**Comment by TobiasNx** [comment]
We got a workaround by using the github searchlink. This is already productiv.
