### ISSUE TITLE
How to update the flux commands page with the links?

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-documentation#47]
@dr0i we talked about that we should now use the metafacture runner to create the flux command page but for me it is still not clear how to add the links to the examples in the playground to the documentation

https://github.com/metafacture/metafacture-documentation/blob/master/docs/Documentation-Maintainer-Guide.md does not explain this.

**Comment by dr0i** [comment]
I've updated https://github.com/metafacture/metafacture-documentation/blob/master/docs/Documentation-Maintainer-Guide.md#how-to-publish-docsfluxflux-commandsmd - basically linking to  https://github.com/metafacture/metafacture-fix/wiki/Maintainer-Guidelines#update-flux-commands.

**Comment by TobiasNx** [comment]
Thanks worked!!!
