### ISSUE TITLE
Examination of documentation status 

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-documentation#8]
We realized that the documentation of Metafacture is scattered, often not linked to each other and sometimes outdated.
To improve the documentation we first have to get an overview of the existing documenation. To examine all parts of the documentation we want to create a table in this repository and add the following informationen to this table:

- URL to documentation
- short description
- target group: User vs. Developer
- up to date? (last update)
- written in which language
- what does the documentation belong to? (core, fix, morph, extension, ...)
- does the page need a link to metafacture.org?

The goal of this ticket is to create the table as described above to form a basis with wich we can discuss the next steps.

**Comment by TobiasNx** [comment]
Should we split the wiki, since it has multiple pages? some of them are newer and some outdated.

**Comment by TobiasNx** [comment]
I would propose to create a dokumentation not in the Wiki but as part of the metafacture site. As:

https://gitlab.com/swissbib/metamorph-doku

**Comment by fsteeg** [comment]
Table moved to https://service-wiki.hbz-nrw.de/display/SEM/Collection+of+existing+Metafacture+documentation

**Comment by katauber** [comment]
You find the results of the examination: https://pad.gwdg.de/sPO-_BEeSmWLMEQUyXYfBQ?view
